image: python:3.10-alpine

stages:
- test
- build
- deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
  - .cache/pip
  - venv/

sast:
  stage: test

python-build:
  stage: build
  script:
  - apk add --no-cache zip mariadb-connector-c
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - zip -r lambda.zip . -x "**/__pycache__/*" ".git/*" ".idea/*"
  artifacts:
    expire_in: 1 week
    paths:
    - lambda.zip

trigger-cdk:
  stage: deploy
  trigger:
    project: $CDK_DOWNSTREAM_PROJECT
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

include:
- template: Security/SAST.gitlab-ci.yml
