image: python:3.10

stages:
- test
- build
- deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
  - .cache/pip
  - venv/

sast:
  stage: test

python-build:
  stage: build
  script:
  - apt update
  - apt install zip
  - mkdir package
  - 'pip install --platform manylinux2014_x86_64 --implementation cp --python-version 3.10 --only-binary=:all: --upgrade pip install --target ./package -r requirements.txt'
  - deactivate
  - cd package
  - zip -r ../lambda.zip . -x  "__pycache__/*" "**/__pycache__/*"
  - cd ../free-market-fandango-api
  - zip -r ../lambda.zip .
  artifacts:
    expire_in: 1 week
    paths:
    - lambda.zip

trigger-cdk:
  stage: deploy
  trigger:
    project: $CDK_DOWNSTREAM_PROJECT
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

include:
- template: Security/SAST.gitlab-ci.yml
