default:
  image:
    name: python:3.13

stages:
  - build

build-zip:
  stage: build

  before_script:
    - apt update
    - apt install zip -y

  script:
    - pip install -r requirements.txt -t /asset-output
    - cp -au . /asset-output
    - zip -r $CI_PROJECT_NAME.zip /asset-output

  artifacts:
    paths:
      - $CI_PROJECT_NAME.zip
