stages:
  - test
  - build
  - deploy

sast:
  stage: test

python-build:
  stage: build
  image: python:3.10
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  script:
  - cd free-market-fandango-api
  - pip install -r requirements.txt -t .
  artifacts:
    paths:
      - free-market-fandango-api/
cdk-deploy:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.dylanw.dev
  image: gitlab.dylanw.dev:5050/images/nodejs-aws-cli:latest
  stage: deploy
  script:
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - npm install --progress=false
    - npm run build
    - npm run cdk bootstrap
    - npm run cdk deploy -- --require-approval=never
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - template: Security/SAST.gitlab-ci.yml
