default:
  image:
    name: python:3.12

stages:
  - build

build-zip:
  stage: build

  before_script:
    - apt update
    - apt install zip -y

  script:
    - pip install -r requirements.txt -t /build
    - cp -au . /build
    - cd /build
    - zip -r /$CI_PROJECT_NAME.zip .

  artifacts:
    paths:
      - /$CI_PROJECT_NAME.zip
